import { createElement } from 'lwc';
import ScheduledMaintenanceComponent from 'c/scheduledMaintenanceComponent';
import getActiveScheduledMaintenances from '@salesforce/apex/ScheduledMaintenanceService.getActiveScheduledMaintenances';
import getAppIdByDeveloperName from '@salesforce/apex/ScheduledMaintenanceService.getAppIdByDeveloperName';
import getUserLocaleInfo from '@salesforce/apex/ScheduledMaintenanceService.getUserLocaleInfo';
import getUserProfileName from '@salesforce/apex/ScheduledMaintenanceService.getUserProfileName';

// Undefined outside Experience Cloud; set per test to simulate a site.
let mockCommunityId;
jest.mock('@salesforce/community/Id', () => ({ __esModule: true, get default() { return mockCommunityId; } }));
jest.mock('@salesforce/apex/ScheduledMaintenanceService.getActiveScheduledMaintenances', () => ({ default: jest.fn() }), { virtual: true });
jest.mock('@salesforce/apex/ScheduledMaintenanceService.getAppIdByDeveloperName', () => ({ default: jest.fn() }), { virtual: true });
jest.mock('@salesforce/apex/ScheduledMaintenanceService.getUserLocaleInfo', () => ({ default: jest.fn() }), { virtual: true });
jest.mock('@salesforce/apex/ScheduledMaintenanceService.getUserProfileName', () => ({ default: jest.fn() }), { virtual: true });

// An in-progress, non-dismissible maintenance for CRM only: an app lock, not a full system lock.
const APP_LOCK_MAINTENANCE = {
    Id: 'a00000000000001AAA',
    Subject__c: 'CRM upgrade',
    Description__c: 'CRM is unavailable',
    Start_Date_Time__c: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    End_Date_Time__c: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    Alert_Frequency__c: 'Daily',
    Dismissible__c: false,
    Applicable_Apps__c: 'CRM'
};

// Lets the chained Apex promises in connectedCallback settle.
const flushPromises = () => new Promise((resolve) => setTimeout(resolve, 0));

describe('c-scheduled-maintenance-component', () => {
    beforeEach(() => {
        mockCommunityId = undefined;
        getUserProfileName.mockResolvedValue('Standard User');
        getUserLocaleInfo.mockResolvedValue({ timeZone: 'America/Los_Angeles', locale: 'en_US' });
        getActiveScheduledMaintenances.mockResolvedValue([]);
        getAppIdByDeveloperName.mockResolvedValue(null);
    });

    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    describe('exit app button', () => {
        async function renderAppLock(props = {}) {
            getActiveScheduledMaintenances.mockResolvedValue([APP_LOCK_MAINTENANCE]);
            const element = createElement('c-scheduled-maintenance-component', {
                is: ScheduledMaintenanceComponent
            });
            Object.assign(element, { currentAppContext: 'CRM' }, props);
            document.body.appendChild(element);
            await flushPromises();
            return element;
        }

        const getFooterButtons = (element) => element.shadowRoot.querySelectorAll('footer lightning-button');

        it('navigates to the Welcome app by default when it is found', async () => {
            getAppIdByDeveloperName.mockResolvedValue('06m000000000001AAA');

            const element = await renderAppLock();

            expect(getAppIdByDeveloperName).toHaveBeenCalledWith({ developerName: 'Welcome' });
            const buttons = getFooterButtons(element);
            expect(buttons).toHaveLength(1);
            expect(buttons[0].label).toBe('Navigate to Welcome App');
        });

        it('uses the configured exit app developer name', async () => {
            getAppIdByDeveloperName.mockResolvedValue('06m000000000002AAA');

            const element = await renderAppLock({ exitAppDeveloperName: 'Sales_Console' });

            expect(getAppIdByDeveloperName).toHaveBeenCalledWith({ developerName: 'Sales_Console' });
            expect(getFooterButtons(element)[0].label).toBe('Navigate to Sales_Console App');
        });

        it('is hidden when the exit app is not found', async () => {
            getAppIdByDeveloperName.mockResolvedValue(null);

            const element = await renderAppLock();

            expect(element.shadowRoot.querySelector('section[role="dialog"]')).not.toBeNull();
            expect(getFooterButtons(element)).toHaveLength(0);
        });

        it('is hidden on Experience Cloud sites without looking up the app', async () => {
            mockCommunityId = '0DB000000000001AAA';
            getAppIdByDeveloperName.mockResolvedValue('06m000000000001AAA');

            const element = await renderAppLock();

            expect(getAppIdByDeveloperName).not.toHaveBeenCalled();
            expect(element.shadowRoot.querySelector('section[role="dialog"]')).not.toBeNull();
            expect(getFooterButtons(element)).toHaveLength(0);
        });
    });
});
