import { createElement } from 'lwc';
import ScheduledMaintenanceComponent from 'c/scheduledMaintenanceComponent';
import getActiveScheduledMaintenances from '@salesforce/apex/ScheduledMaintenanceService.getActiveScheduledMaintenances';
import getAppIdByDeveloperName from '@salesforce/apex/ScheduledMaintenanceService.getAppIdByDeveloperName';
import getUserLocaleInfo from '@salesforce/apex/ScheduledMaintenanceService.getUserLocaleInfo';

jest.mock(
    '@salesforce/apex/ScheduledMaintenanceService.getActiveScheduledMaintenances',
    () => ({ default: jest.fn() }),
    { virtual: true }
);
jest.mock(
    '@salesforce/apex/ScheduledMaintenanceService.getAppIdByDeveloperName',
    () => ({ default: jest.fn() }),
    { virtual: true }
);
jest.mock(
    '@salesforce/apex/ScheduledMaintenanceService.getUserLocaleInfo',
    () => ({ default: jest.fn() }),
    { virtual: true }
);

// Flush all pending promise microtasks
async function flushPromises() {
    for (let i = 0; i < 10; i++) {
        // eslint-disable-next-line no-await-in-loop
        await Promise.resolve();
    }
}

function isoOffset(ms) {
    return new Date(Date.now() + ms).toISOString();
}

const HOUR = 60 * 60 * 1000;

function baseRecord(overrides = {}) {
    return {
        Id: 'rec001',
        Start_Date_Time__c: isoOffset(-HOUR),
        End_Date_Time__c: isoOffset(HOUR),
        Dismissible__c: true,
        Applicable_Apps__c: 'TestApp',
        Alert_Frequency__c: 'Every Visit',
        Subject__c: 'Test Maintenance',
        Description__c: 'Test description',
        Alert_Buffer__c: 0,
        ...overrides
    };
}

// Find a lightning-button stub element by its label property
function findButtonByLabel(root, label) {
    return Array.from(root.querySelectorAll('lightning-button')).find(el => el.label === label) || null;
}

describe('c-scheduled-maintenance-component', () => {
    beforeEach(() => {
        // Provide safe default mocks so tests that don't care about Apex don't throw
        getActiveScheduledMaintenances.mockResolvedValue([]);
        getAppIdByDeveloperName.mockResolvedValue(null);
        getUserLocaleInfo.mockResolvedValue({ timeZone: 'UTC', locale: 'en-US' });
    });

    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    // --- Footer button rendering driven by showNavigateButton / isDismissible ---

    describe('footer button rendering', () => {
        beforeEach(() => {
            jest.useFakeTimers();
        });

        afterEach(() => {
            jest.useRealTimers();
        });

        async function mountWith(records) {
            getActiveScheduledMaintenances.mockResolvedValue(records);
            const element = createElement('c-scheduled-maintenance-component', {
                is: ScheduledMaintenanceComponent
            });
            document.body.appendChild(element);
            await flushPromises();
            return element;
        }

        it('shows Dismiss button and hides Navigate button when active maintenance is dismissible', async () => {
            const el = await mountWith([baseRecord({ Dismissible__c: true })]);

            expect(findButtonByLabel(el.shadowRoot, 'Dismiss')).not.toBeNull();
            expect(findButtonByLabel(el.shadowRoot, 'Navigate to Welcome App')).toBeNull();
        });

        it('shows Navigate button and hides Dismiss button for a non-system app-lock (isDismissible=false, isFullLock=false)', async () => {
            const el = await mountWith([baseRecord({ Dismissible__c: false, Applicable_Apps__c: 'App1' })]);

            expect(findButtonByLabel(el.shadowRoot, 'Navigate to Welcome App')).not.toBeNull();
            expect(findButtonByLabel(el.shadowRoot, 'Dismiss')).toBeNull();
        });

        it('hides both buttons during a full system lock (isDismissible=false, isFullLock=true)', async () => {
            const el = await mountWith([baseRecord({ Dismissible__c: false, Applicable_Apps__c: 'System' })]);

            expect(findButtonByLabel(el.shadowRoot, 'Navigate to Welcome App')).toBeNull();
            expect(findButtonByLabel(el.shadowRoot, 'Dismiss')).toBeNull();
        });
    });
});