import { createElement } from 'lwc';
import ScheduledMaintenanceComponent from 'c/scheduledMaintenanceComponent';
import getActiveScheduledMaintenances from '@salesforce/apex/ScheduledMaintenanceService.getActiveScheduledMaintenances';
import getUserLocaleInfo from '@salesforce/apex/ScheduledMaintenanceService.getUserLocaleInfo';
import getAppIdByDeveloperName from '@salesforce/apex/ScheduledMaintenanceService.getAppIdByDeveloperName';

jest.mock(
    '@salesforce/apex/ScheduledMaintenanceService.getActiveScheduledMaintenances',
    () => ({ default: jest.fn() }),
    { virtual: true }
);
jest.mock(
    '@salesforce/apex/ScheduledMaintenanceService.getUserLocaleInfo',
    () => ({ default: jest.fn() }),
    { virtual: true }
);
jest.mock(
    '@salesforce/apex/ScheduledMaintenanceService.getAppIdByDeveloperName',
    () => ({ default: jest.fn() }),
    { virtual: true }
);

// Helper to flush all pending promises
const flushPromises = () => new Promise((resolve) => setTimeout(resolve, 0));

const MOCK_MAINTENANCE = [
    {
        Id: 'a001',
        Subject__c: 'Test Maintenance',
        Description__c: 'Maintenance description',
        Start_Date_Time__c: '2020-01-01T00:00:00.000Z',
        End_Date_Time__c: '2099-12-31T23:59:59.000Z',
        Dismissible__c: true,
        Alert_Frequency__c: 'Every Visit',
        Applicable_Apps__c: 'TestApp'
    }
];

describe('c-scheduled-maintenance-component', () => {
    beforeEach(() => {
        getActiveScheduledMaintenances.mockResolvedValue(MOCK_MAINTENANCE);
        getUserLocaleInfo.mockResolvedValue({ timeZone: 'UTC', locale: 'en-US' });
        getAppIdByDeveloperName.mockResolvedValue('testAppId');
    });

    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    it('modal section has aria-labelledby and aria-describedby when open', async () => {
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });
        document.body.appendChild(element);
        await flushPromises();

        const section = element.shadowRoot.querySelector('section[role="dialog"]');
        expect(section).not.toBeNull();
        // LWC scopes IDs with a suffix, so check with toContain
        expect(section.getAttribute('aria-labelledby')).toContain('modal-heading-01');
        expect(section.getAttribute('aria-describedby')).toContain('modal-content-01');
        expect(section.getAttribute('aria-modal')).toBe('true');
    });

    it('modal title h2 has id matching aria-labelledby', async () => {
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });
        document.body.appendChild(element);
        await flushPromises();

        // LWC scopes IDs with a suffix, so use an attribute contains selector
        const heading = element.shadowRoot.querySelector('h2[id*="modal-heading-01"]');
        expect(heading).not.toBeNull();
        expect(heading.id).toContain('modal-heading-01');
    });

    it('modal content div has id matching aria-describedby', async () => {
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });
        document.body.appendChild(element);
        await flushPromises();

        // LWC scopes IDs with a suffix, so use an attribute contains selector
        const contentDiv = element.shadowRoot.querySelector('div[id*="modal-content-01"]');
        expect(contentDiv).not.toBeNull();
        expect(contentDiv.id).toContain('modal-content-01');
    });

    it('pressing Escape key on the modal section does not throw an error', async () => {
        const element = createElement('c-scheduled-maintenance-component', {
            is: ScheduledMaintenanceComponent
        });
        document.body.appendChild(element);
        await flushPromises();

        const section = element.shadowRoot.querySelector('section[role="dialog"]');
        expect(section).not.toBeNull();
        const escapeEvent = new KeyboardEvent('keydown', { key: 'Escape', bubbles: true });
        expect(() => section.dispatchEvent(escapeEvent)).not.toThrow();
    });
});